In [14]:
import pandas as pd

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [16]:
df= pd.read_csv('../ETL/games.csv')

In [17]:
vj= df[['id','title']].copy()

In [18]:
vj

             id                     title
0      761140.0       Lost Summoner Kitty
1      643980.0                 Ironbound
2      670290.0   Real Pool 3D - Poolians
3      767400.0                   弹炸人2222
4      773570.0                       NaN
...         ...                       ...
32130  773640.0            Colony On Mars
32131  733530.0  LOGistICAL: South Africa
32132  610660.0             Russian Roads
32133  658870.0       EXIT 2 - Directions
32134  681550.0                       NaN

[32135 rows x 2 columns]

In [19]:
vj = vj.dropna()

In [20]:
vj=vj.drop_duplicates()

In [21]:
vj

             id                     title
0      761140.0       Lost Summoner Kitty
1      643980.0                 Ironbound
2      670290.0   Real Pool 3D - Poolians
3      767400.0                   弹炸人2222
5      772540.0     Battle Royale Trainer
...         ...                       ...
32129  745400.0              Kebab it Up!
32130  773640.0            Colony On Mars
32131  733530.0  LOGistICAL: South Africa
32132  610660.0             Russian Roads
32133  658870.0       EXIT 2 - Directions

[30083 rows x 2 columns]

In [22]:
vj =vj.head(20000)

In [23]:
vj

             id                                              title
0      761140.0                                Lost Summoner Kitty
1      643980.0                                          Ironbound
2      670290.0                            Real Pool 3D - Poolians
3      767400.0                                            弹炸人2222
5      772540.0                              Battle Royale Trainer
...         ...                                                ...
21786  519240.0  Kalen Chock Presents: Approaching and Explorin...
21787  519212.0              Daylight's End VR Edition - Chapter 3
21788  519216.0              Daylight's End VR Edition - Chapter 7
21789  519210.0              Daylight's End VR Edition - Chapter 1
21790  519214.0              Daylight's End VR Edition - Chapter 5

[20000 rows x 2 columns]

In [11]:
import pandas as pd

# Cargar el conjunto de datos
data = pd.read_csv("../Funciones/title.csv")

# Verificar si hay valores nulos o faltantes en la columna de títulos
if data["title"].isnull().any():
    print("Hay valores nulos o faltantes en la columna de títulos.")
else:
    # Contar la cantidad de id únicos y títulos no nulos
    unique_ids = data["id"].nunique()
    non_null_titles = data["title"].count()

    # Verificar si cada id tiene un título asociado
    if unique_ids == non_null_titles:
        print("Cada id tiene un título asociado.")
    else:
        print("Algunos ids no tienen títulos asociados.")

Cada id tiene un título asociado.

In [13]:
vj

             id                     title
0      761140.0       Lost Summoner Kitty
1      643980.0                 Ironbound
2      670290.0   Real Pool 3D - Poolians
3      767400.0                   弹炸人2222
4      772540.0     Battle Royale Trainer
...         ...                       ...
30078  745400.0              Kebab it Up!
30079  773640.0            Colony On Mars
30080  733530.0  LOGistICAL: South Africa
30081  610660.0             Russian Roads
30082  658870.0       EXIT 2 - Directions

[30083 rows x 2 columns]

In [24]:
vj.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20000 entries, 0 to 21790
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20000 non-null  float64
 1   title   20000 non-null  object
dtypes: float64(1), object(1)
memory usage: 468.8+ KB

In [25]:
vj.to_csv('title.csv', index=False)

In [26]:
#Visualizo el csv videojuegos
vj= pd.read_csv('../Funciones/title.csv')

#Creo un vectorizador Tf-IDF para procesar el texto de las sinopsis (title)
tfidf =TfidfVectorizer(stop_words='english')

#Llenar los valores nulos en la columna title con una cadena vacia
vj['title']=vj['title'].fillna("")

#Calculo la matriz TF-IDF para la sinopsis 
tfidf_matriz= tfidf.fit_transform(vj['title'])

#Calcular la similitud del coseno entre las sinopsis utilizando la matriz TF-IDF
coseno_similitud= linear_kernel(tfidf_matriz,tfidf_matriz)

In [27]:
#Crear una serie de pandas para mapear los titulos de los videos juegos a sus indices en el dataset
indices= pd.Series(vj.index, vj['title'].drop_duplicates)

# Establecer la columna "title" como índice del DataFrame
data = data.set_index("title")

#Obtener el indice del videojuego ingresado como parametro
indice= indices[titulo]

#Enumere las similitudes coseno de los videojuegos con todos los demas videojuegos
similitud = list(enumerate(coseno_similitud[indice]))

TypeError: 'method' object is not iterable

In [101]:
#Obtener el indice del videojuego ingresado como parametro
indice= indices[titulo]

#Enumere las similitudes coseno de los videojuegos con todos los demas videojuegos
similitud = list(enumerate(coseno_similitud[indice]))

#Obtner los videojuegos segun su similitud coseno en orden descendente
similitud= sorted(similitud, key=lambda x: x[1], reverse =True)

#Excluir el videojuego consultado y seleccionar los videojuegos mas similares
similitud= similitud[1:11]

#Obtener los indices de los videojuegos recomendados
videojuego_index=[vj[0] for i in similares]

#Obtener la lista de titulos de los 5 videojuegos recomendados 
lista= vj['title'].iloc[videojuego_index].to_list()[:5]

#Devolver un diccionario con la lista de los videojuegos
return {'lista recomendada':lista}

NameError: name 'indices' is not defined

In [56]:
#Crear una serie de pandas para mapear los titulos de los videos juegos a sus indices en el dataset
indices=pd.Series(vj.index, vj['title'].drop_duplicates)

#Obtener el indice del videojuego ingresado como parametro
indice=indices[titulo]

#Enumere las similitudes coseno de los videojuegos con todos los demas videojuegos
simil=list(enumerate(coseno_similitud[indice]))

#Obtner los videojuegos segun su similitud coseno en orden descendente
similares= scorted(similares, key=lambda x: x[1], reverse =True)

#Excluir el videojuego consultado y seleccionar los videojuegos mas similares
similares=similares[1:11]

#Obtener los indices de los videojuegos recomendados
videojuego_index=[vj[0] for i in similares]

#Obtener la lista de titulos de los 5 videojuegos recomendados 
lista= vj['title'].iloc[videojuego_index].to_list()[:5]

#Devolver un diccionario con la lista de los videojuegos
return {'lista recomendada':lista}

TypeError: 'method' object is not iterable

In [19]:
def recomendacion(id):
    '''Ingrese el id de producto, te recomiendara 5 videojuegos similares'''

#Visualizo el csv videojuegos
vj= pd.read_csv('../Funciones/title.csv')

#Creo un vectorizador Tf-IDF para procesar el texto de las sinopsis (title)
tfidf =TfidfVectorizer(stop_words='english')

#Llenar los valores nulos en la columna title con una cadena vacia
vj['title']=vj['title'].fillna("")

#Calculo la matriz TF-IDF para la sinopsis 
tfidf_matriz= tfidf.fit_transform(vj['title'])

#Calcular la similitud del coseno entre las sinopsis utilizando la matriz TF-IDF
coseno_similitud= linear_kernel(tfidf_matriz,tfidf_matriz)

#Crear una serie de pandas para mapear los titulos de los videos juegos a sus indices en el dataset
indices=pd.Serie(vj.index, vj['title'].drop.duplicates)

#Obtener el indice del videojuego ingresado como parametro
indice=indices[titulo]

#Enumere las similitudes coseno de los videojuegos con todos los demas videojuegos
simil=list(enumerate(coseno_similitud[indice]))

#Obtner los videojuegos segun su similitud coseno en orden descendente
similares= scorted(similares, key=lambda x: x[1], reverse =True)

#Excluir el videojuego consultado y seleccionar los videojuegos mas similares
similares=similares[1:11]

#Obtener los indices de los videojuegos recomendados
videojuego_index=[vj[0] for i in similares]

#Obtener la lista de titulos de los 5 videojuegos recomendados 
lista= vj['title'].iloc[videojuego_index].to_list()[:5]

#Devolver un diccionario con la lista de los videojuegos
return {'lista recomendada':lista}