Vamos a realizar ETL. Para lo cual comenzaré importando las librerias que necesito

In [1]:
import pandas as pd  
import json 
import gzip
import ast

Crearé una función para ver el archivo 'stem_games.json.gz' que está comprimido y luego crearé un dataset df_games

In [6]:
def ver():
    with gzip.open('../DATA/steam_games.json.gz','rt', encoding='utf-8') as f:
        return [json.loads(line.strip())
            for line in f]

data_games = ver()

df_games = pd.DataFrame(data_games)

Vamos a ver el dataset

In [3]:
df_games

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,discount_price,specs,price,early_access,id,metascore,developer,user_id,steam_id,items,items_count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76561197970982479,76561197970982479,"[{'item_id': '10', 'item_name': 'Counter-Strik...",277.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,js41637,76561198035864385,"[{'item_id': '10', 'item_name': 'Counter-Strik...",888.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,evcentric,76561198007712555,"[{'item_id': '1200', 'item_name': 'Red Orchest...",137.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Riot-Punch,76561197963445855,"[{'item_id': '10', 'item_name': 'Counter-Strik...",328.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,doctr,76561198002099482,"[{'item_id': '300', 'item_name': 'Day of Defea...",541.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,1.49,"[Single-player, Steam Achievements]",1.99,False,773640,NaN,"Nikita ""Ghost_RUS""",NaN,NaN,NaN,NaN
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,4.24,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,NaN,Sacada,NaN,NaN,NaN,NaN
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,1.39,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,NaN,Laush Dmitriy Sergeevich,NaN,NaN,NaN,NaN
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,NaN,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,NaN,"xropi,stev3ns",NaN,NaN,NaN,NaN
120444,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,NaN,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,NaN,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN,NaN,NaN,NaN,NaN,NaN

Vamos a ver la informacion del datasest

In [7]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120445 entries, 0 to 120444
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   publisher       24083 non-null  object
 1   genres          28852 non-null  object
 2   app_name        32133 non-null  object
 3   title           30085 non-null  object
 4   url             32135 non-null  object
 5   release_date    30068 non-null  object
 6   tags            31972 non-null  object
 7   reviews_url     32133 non-null  object
 8   discount_price  225 non-null    float64
 9   specs           31465 non-null  object
 10  price           30758 non-null  object
 11  early_access    32135 non-null  object
 12  id              32133 non-null  object
 13  metascore       2677 non-null   object
 14  developer       28836 non-null  object
 15  user_id         88310 non-null  object
 16  steam_id        88310 non-null  object
 17  items           88310 non-null  object
 18  items_count     88310 non-null  float64
dtypes: float64(2), object(17)
memory usage: 17.5+ MB

Eliminaré las filas que contienen valores nulos desde la columna de posicion 0 a la de posicion 14.Porque luego eliminaré las ultimas 4 columnas porque se encuentran en los otros archivos.

In [8]:
df_games = df_games.dropna(subset=df_games.iloc[:, :15].columns, how='all')

In [9]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32135 entries, 88310 to 120444
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   publisher       24083 non-null  object
 1   genres          28852 non-null  object
 2   app_name        32133 non-null  object
 3   title           30085 non-null  object
 4   url             32135 non-null  object
 5   release_date    30068 non-null  object
 6   tags            31972 non-null  object
 7   reviews_url     32133 non-null  object
 8   discount_price  225 non-null    float64
 9   specs           31465 non-null  object
 10  price           30758 non-null  object
 11  early_access    32135 non-null  object
 12  id              32133 non-null  object
 13  metascore       2677 non-null   object
 14  developer       28836 non-null  object
 15  user_id         0 non-null      object
 16  steam_id        0 non-null      object
 17  items           0 non-null      object
 18  items_count     0 non-null      float64
dtypes: float64(2), object(17)
memory usage: 4.9+ MB

Eliminar columnas porque estas columnas ya las tengo en otros archivos

In [10]:
df_games= df_games.drop('user_id', axis=1)

In [11]:
df_games=df_games.drop('steam_id', axis=1)

In [12]:
df_games=df_games.drop('items', axis=1)

In [13]:
df_games=df_games.drop('items_count', axis=1)

In [14]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32135 entries, 88310 to 120444
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   publisher       24083 non-null  object
 1   genres          28852 non-null  object
 2   app_name        32133 non-null  object
 3   title           30085 non-null  object
 4   url             32135 non-null  object
 5   release_date    30068 non-null  object
 6   tags            31972 non-null  object
 7   reviews_url     32133 non-null  object
 8   discount_price  225 non-null    float64
 9   specs           31465 non-null  object
 10  price           30758 non-null  object
 11  early_access    32135 non-null  object
 12  id              32133 non-null  object
 13  metascore       2677 non-null   object
 14  developer       28836 non-null  object
dtypes: float64(1), object(14)
memory usage: 3.9+ MB

Crearé un csv games.csv a partir del df_games

In [15]:
df_games.to_csv('games.csv', index=False, errors='replace')

Voy a descomprimir el archivo user_reviews.json.gz y crearé un dataset df_reviews

In [43]:
def ver():
    with gzip.open('../DATA/user_reviews.json.gz','rt', encoding='utf-8') as f:
        return [ast.literal_eval(line.strip())
            for line in f]

data_reviews = ver()

df_reviews = pd.DataFrame(data_reviews)

In [44]:
df_reviews

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."
...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la..."
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l..."
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',..."
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l..."
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',..."

In [45]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25799 entries, 0 to 25798
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user_id   25799 non-null  object
 1   user_url  25799 non-null  object
 2   reviews   25799 non-null  object
dtypes: object(3)
memory usage: 604.8+ KB

Crearé una columna funny en el dataset reviews.

In [46]:
df_reviews['funny']= df_reviews['reviews'].apply(lambda x :[d['funny'] for d in x])

Crearé una columna posted en el dataset reviews

In [47]:
df_reviews['posted']=df_reviews['reviews'].apply(lambda x :[d['posted']for d in x])

Crearé una columna last_edited en el dataset reviews

In [48]:
df_reviews['last_edited']= df_reviews['reviews'].apply(lambda x:[d['last_edited']for d in x])

In [49]:
df_reviews['item_id']= df_reviews['reviews'].apply(lambda x:[d['item_id']for d in x])

Crearé una columna helpful en el dataset reviews

In [50]:
df_reviews['helpful']= df_reviews['reviews'].apply(lambda x :[d['helpful'] for d in x])

Crearé una columna recommend en el dataset reviews

In [51]:
df_reviews['recommend']= df_reviews['reviews'].apply(lambda x :[d['recommend'] for d in x])

Crearé una columna review1 en el dataset reviews

In [52]:
df_reviews['review1']= df_reviews['reviews'].apply(lambda x :[d['review'] for d in x])

Vamos a ver como quedo el dataset

In [53]:
df_reviews

,user_id,user_url,reviews,funny,posted,last_edited,item_id,helpful,recommend,review1
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","[Posted November 5, 2011., Posted July 15, 201...","[, , ]","[1250, 22200, 43110]","[No ratings yet, No ratings yet, No ratings yet]","[True, True, True]",[Simple yet with great replayability. In my op...
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014...","[, , ]","[Posted June 24, 2014., Posted September 8, 20...","[, , ]","[251610, 227300, 239030]",[15 of 20 people (75%) found this review helpf...,"[True, True, True]",[I know what you think when you see this title...
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',...","[, , , , , ]","[Posted February 3., Posted December 4, 2015.,...","[, Last edited December 5, 2015., , , , ]","[248820, 370360, 237930, 263360, 107200, 224500]","[No ratings yet, No ratings yet, No ratings ye...","[True, True, True, True, True, True]",[A suitably punishing roguelike platformer. W...
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2...","[, , , , , ]","[Posted October 14, 2013., Posted July 28, 201...","[, , , , , ]","[250320, 20920, 204100, 224600, 207610, 108710]",[2 of 2 people (100%) found this review helpfu...,"[True, True, True, True, True, True]",[This game... is so fun. The fight sequences h...
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',...","[3 people found this review funny, 1 person fo...","[Posted April 15, 2014., Posted December 23, 2...","[, , , ]","[211420, 211820, 730, 204300]",[35 of 43 people (81%) found this review helpf...,"[True, True, True, True]","[Git gud, It's like Terraria, you play for 9 h..."
...,...,...,...,...,...,...,...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la...",[],[Posted May 31.],[],[261030],[0 of 1 people (0%) found this review helpful],[True],[I cried in the end its so sadding ]'; I wish ...
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l...",[],[Posted June 17.],[],[730],[0 of 1 people (0%) found this review helpful],[True],[Gra naprawdę fajna.Ale jest kilka rzeczy do k...
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',...",[1 person found this review funny],[Posted June 23.],[],[570],[1 of 1 people (100%) found this review helpful],[True],[Well Done]
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l...","[, , , ]","[Posted July 21., Posted July 10., Posted July...","[, , , ]","[233270, 130, 70, 362890]","[No ratings yet, No ratings yet, No ratings ye...","[True, True, True, True]",[this is a very fun and nice 80s themed shoote...
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]","[Posted July 3., Posted July 20., Posted July 2.]","[, , ]","[273110, 730, 440]",[1 of 2 people (50%) found this review helpful...,"[True, True, True]",[had so much fun plaing this and collecting re...

In [54]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25799 entries, 0 to 25798
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      25799 non-null  object
 1   user_url     25799 non-null  object
 2   reviews      25799 non-null  object
 3   funny        25799 non-null  object
 4   posted       25799 non-null  object
 5   last_edited  25799 non-null  object
 6   item_id      25799 non-null  object
 7   helpful      25799 non-null  object
 8   recommend    25799 non-null  object
 9   review1      25799 non-null  object
dtypes: object(10)
memory usage: 2.0+ MB

In [55]:
df_reviews.to_csv('reviews.csv', index=False)

Realizaré el analisis de sentimiento

Vamos a cambiar el tipo de dato de la columna review1 a cadena de texto (string)

In [56]:
df_reviews['review1'] = df_reviews['review1'].astype(str)

Vamos a cambiar a míniscula la columna review1

In [57]:
df_reviews['review1'] = df_reviews['review1'].str.lower()

Importaré la clase TextBlob del módulo textblob.TextBlob es una herramienta de procesamiento de lenguaje 
natural (NLP) que se utiliza para realizar tareas como análisis de sentimientos.

In [58]:
from textblob import TextBlob

Aplicare el analisis de sentimiento a la columna review1 utilizando el metodo sentiment.polarity

In [59]:
df_reviews['sentiment_analysis'] = df_reviews['review1'].apply(lambda x: TextBlob(x).sentiment.polarity)

In [60]:
df_reviews['sentiment_analysis']

0        0.163715
1       -0.009975
2        0.163826
3        0.262340
4        0.436631
           ...
25794    0.400000
25795    0.000000
25796    0.000000
25797    0.162793
25798    0.130000
Name: sentiment_analysis, Length: 25799, dtype: float64

In [61]:
# Asignare una escala de valor según el análisis de sentimiento y crearé la columna score
df_reviews['score'] = df_reviews['sentiment_analysis'].apply(lambda x: 0 if x < -0.1 else (1 if x < 0.1 else 2))

In [62]:
df_reviews['score']

0        2
1        1
2        2
3        2
4        2
        ..
25794    2
25795    1
25796    1
25797    2
25798    2
Name: score, Length: 25799, dtype: int64

In [63]:
df_reviews

,user_id,user_url,reviews,funny,posted,last_edited,item_id,helpful,recommend,review1,sentiment_analysis,score
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","[Posted November 5, 2011., Posted July 15, 201...","[, , ]","[1250, 22200, 43110]","[No ratings yet, No ratings yet, No ratings yet]","[True, True, True]",['simple yet with great replayability. in my o...,0.163715,2
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014...","[, , ]","[Posted June 24, 2014., Posted September 8, 20...","[, , ]","[251610, 227300, 239030]",[15 of 20 people (75%) found this review helpf...,"[True, True, True]",['i know what you think when you see this titl...,-0.009975,1
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',...","[, , , , , ]","[Posted February 3., Posted December 4, 2015.,...","[, Last edited December 5, 2015., , , , ]","[248820, 370360, 237930, 263360, 107200, 224500]","[No ratings yet, No ratings yet, No ratings ye...","[True, True, True, True, True, True]","[""a suitably punishing roguelike platformer. ...",0.163826,2
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2...","[, , , , , ]","[Posted October 14, 2013., Posted July 28, 201...","[, , , , , ]","[250320, 20920, 204100, 224600, 207610, 108710]",[2 of 2 people (100%) found this review helpfu...,"[True, True, True, True, True, True]",['this game... is so fun. the fight sequences ...,0.262340,2
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',...","[3 people found this review funny, 1 person fo...","[Posted April 15, 2014., Posted December 23, 2...","[, , , ]","[211420, 211820, 730, 204300]",[35 of 43 people (81%) found this review helpf...,"[True, True, True, True]","['git gud', ""it's like terraria, you play for ...",0.436631,2
...,...,...,...,...,...,...,...,...,...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la...",[],[Posted May 31.],[],[261030],[0 of 1 people (0%) found this review helpful],[True],"[""i cried in the end its so sadding ]'; i wish...",0.400000,2
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l...",[],[Posted June 17.],[],[730],[0 of 1 people (0%) found this review helpful],[True],['gra naprawdę fajna.ale jest kilka rzeczy do ...,0.000000,1
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',...",[1 person found this review funny],[Posted June 23.],[],[570],[1 of 1 people (100%) found this review helpful],[True],['well done'],0.000000,1
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l...","[, , , ]","[Posted July 21., Posted July 10., Posted July...","[, , , ]","[233270, 130, 70, 362890]","[No ratings yet, No ratings yet, No ratings ye...","[True, True, True, True]",['this is a very fun and nice 80s themed shoot...,0.162793,2
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]","[Posted July 3., Posted July 20., Posted July 2.]","[, , ]","[273110, 730, 440]",[1 of 2 people (50%) found this review helpful...,"[True, True, True]",['had so much fun plaing this and collecting r...,0.130000,2

Voy a dividir una cadena en varias subcadenas para lo cual utilizaré la función explode en las columnas del dataset reviews que necesite ser dividida.

In [73]:
df_reviews

,user_id,user_url,reviews,funny,posted,last_edited,item_id,helpful,recommend,review1,sentiment_analysis,score
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted November 5, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted November 5, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted November 5, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
3,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted July 15, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
4,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted July 15, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
...,...,...,...,...,...,...,...,...,...,...,...,...
1423596,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 20.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423597,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 20.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423598,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 2.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423599,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 2.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423600,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 2.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2

In [22]:
df_reviews = df_reviews.explode('item_id').reset_index(drop=True)

In [23]:
df_reviews=df_reviews.explode('posted').reset_index(drop=True)

In [24]:
df_reviews=df_reviews.explode('recommend').reset_index(drop=True)

In [41]:
df_reviews=df_reviews.explode('review1').reset_index(drop=True)

In [26]:
df_reviews

,user_id,user_url,reviews,funny,posted,last_edited,item_id,helpful,recommend,review1,sentiment_analysis,score
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted November 5, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted November 5, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted November 5, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
3,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted July 15, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
4,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...","[, , ]","Posted July 15, 2011.","[, , ]",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,0.163715,2
...,...,...,...,...,...,...,...,...,...,...,...,...
1423596,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 20.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423597,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 20.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423598,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 2.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423599,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 2.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2
1423600,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...","[1 person found this review funny, , ]",Posted July 2.,"[, , ]",440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,0.130000,2

In [ ]:
Eliminaré columnas

Eliminaré la columna 'reviews' ya que desanide los datos necesarios

In [74]:
df_reviews= df_reviews.drop('reviews', axis=1)

Eliminaré la columna 'funny' porque no la utilizaré en las funciones

In [75]:
df_reviews= df_reviews.drop('funny', axis=1)

Eliminaré la columna 'last_edited' porque no la utilizaré. Para realizar una funcion referida a fecha  tendré en cuenta solo la columna 'posted'

In [76]:
df_reviews= df_reviews.drop('last_edited', axis=1)

Eliminaré la columna 'sentiment_analysis' porque está solo es un paso previo para obtener el analisis de sentimiento que se encuentra en la columna score

In [77]:
df_reviews=df_reviews.drop('sentiment_analysis', axis=1)

Cambiaré el nombre de la columna 'score' por user_review

In [78]:
df_reviews = df_reviews.rename(columns={'score': 'user_review'})

In [79]:
df_reviews

,user_id,user_url,posted,item_id,helpful,recommend,review1,user_review
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted November 5, 2011.",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,2
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted November 5, 2011.",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,2
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted November 5, 2011.",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,2
3,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted July 15, 2011.",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,2
4,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted July 15, 2011.",1250,"[No ratings yet, No ratings yet, No ratings yet]",True,['simple yet with great replayability. in my o...,2
...,...,...,...,...,...,...,...,...
1423596,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 20.,440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,2
1423597,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 20.,440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,2
1423598,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 2.,440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,2
1423599,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 2.,440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,2
1423600,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 2.,440,[1 of 2 people (50%) found this review helpful...,True,['had so much fun plaing this and collecting r...,2

In [80]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1423601 entries, 0 to 1423600
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   user_id      1423601 non-null  object
 1   user_url     1423601 non-null  object
 2   posted       1423601 non-null  object
 3   item_id      1423601 non-null  object
 4   helpful      1423601 non-null  object
 5   recommend    1423601 non-null  object
 6   review1      1423601 non-null  object
 7   user_review  1423601 non-null  int64
dtypes: int64(1), object(7)
memory usage: 86.9+ MB

Del dataset reviews voy a crear un csv

In [81]:
df_reviews.to_csv('reviews.csv', index=False, errors='replace')

Vamos a descomprimir el archivo gz y crearé un dataset df_items

In [6]:
def ver():
    with gzip.open('../DATA/users_items.json.gz','rt', encoding='utf-8') as f:
        return [ast.literal_eval(line.strip())
            for line in f]

data_items = ver()

df_items = pd.DataFrame(data_items)

Crearé una columna item_id en el dataset items

In [7]:
df_items['item_id']= df_items['items'].apply(lambda x :[d['item_id'] for d in x])

Crearé una columna item_name en el dataset items

In [8]:
df_items['item_name']= df_items['items'].apply(lambda x :[d['item_name'] for d in x])

Crearé una columna playtime_forever en el dataset items

In [9]:
df_items['playtime_forever']= df_items['items'].apply(lambda x :[d['playtime_forever'] for d in x])

Crearé una columna playtime_2weeks en el datast items

In [10]:
df_items['playtime_2weeks']= df_items['items'].apply(lambda x :[d['playtime_2weeks'] for d in x])

In [11]:
df_items

,user_id,items_count,steam_id,user_url,items,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik...","[10, 20, 30, 40, 50, 60, 70, 130, 300, 240, 38...","[Counter-Strike, Team Fortress Classic, Day of...","[6, 0, 7, 0, 0, 0, 0, 0, 4733, 1853, 333, 75, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik...","[10, 80, 100, 300, 30, 40, 60, 240, 280, 360, ...","[Counter-Strike, Counter-Strike: Condition Zer...","[0, 0, 0, 220, 0, 0, 0, 62, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest...","[1200, 1230, 1280, 1520, 220, 320, 340, 360, 3...","[Red Orchestra: Ostfront 41-45, Mare Nostrum, ...","[923, 0, 0, 158, 1323, 0, 90, 0, 234, 113, 507...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik...","[10, 20, 30, 40, 50, 60, 70, 130, 80, 100, 300...","[Counter-Strike, Team Fortress Classic, Day of...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 67, 2304, 0, 0,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea...","[300, 20, 50, 70, 130, 10, 30, 40, 60, 80, 100...","[Day of Defeat: Source, Team Fortress Classic,...","[1131, 89, 178, 108, 313, 93, 16, 4, 0, 13, 47...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...,...,...,...
88305,76561198323066619,22,76561198323066619,http://steamcommunity.com/profiles/76561198323...,"[{'item_id': '413850', 'item_name': 'CS:GO Pla...","[413850, 413851, 413852, 413853, 413854, 41385...","[CS:GO Player Profiles, CS:GO Player Profiles:...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
88306,76561198326700687,177,76561198326700687,http://steamcommunity.com/profiles/76561198326...,"[{'item_id': '11020', 'item_name': 'TrackMania...","[11020, 6370, 13140, 51100, 107900, 113400, 20...","[TrackMania Nations Forever, Bloodline Champio...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
88307,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,[],[],[],[],[]
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"[{'item_id': '304930', 'item_name': 'Unturned'...","[304930, 227940, 346330, 373330, 388490, 52157...","[Unturned, Heroes & Generals, BrainBread 2, Al...","[677, 43, 0, 0, 3, 4, 3]","[677, 43, 0, 0, 3, 4, 3]"
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,[],[],[],[],[]

Crearé un csv a partir del df_items

In [12]:
df_items.to_csv('items.csv', index=False, errors='replace')